version: '3.8'

services:
  allegutta-proxy:
    image: bisand/allegutta-proxy:latest
    ports:
      - '18080:80'
    restart: always
    depends_on:
      - allegutta-api
      - allegutta-web
      - allegutta-db
    deploy:
      mode: replicated
      replicas: 1

  allegutta-web:
    image: bisand/allegutta-web:latest
    depends_on:
      - allegutta-api
    restart: always
    deploy:
      mode: replicated
      replicas: 1

  allegutta-api:
    image: bisand/allegutta-api:latest
    depends_on:
      - allegutta-proxy
      - allegutta-db
    environment:
      PUPPETEER_EXECUTABLE_PATH: ${PUPPETEER_EXECUTABLE_PATH}
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: ${PUPPETEER_SKIP_CHROMIUM_DOWNLOAD}
      NORDNET_USERNAME: ${NORDNET_USERNAME}
      NORDNET_PASSWORD: ${NORDNET_PASSWORD}
      NORDNET_ACCOUNT: ${NORDNET_ACCOUNT}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      # Data persistency
      - api-data:/app/data
      - api-logs:/app/logs
    restart: always
    deploy:
      mode: replicated
      replicas: 1

  allegutta-db:
    image: yobasystems/alpine-mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    deploy:
      mode: replicated
      replicas: 1

volumes:
  api-data:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.86.175,rw,noatime,nolock,rsize=32768,wsize=32768,tcp,timeo=14
      device: ":/srv/nfs/allegutta/api-data"
  api-logs:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.86.175,rw,noatime,nolock,rsize=32768,wsize=32768,tcp,timeo=14
      device: ":/srv/nfs/allegutta/api-logs"
  db-data:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=192.168.86.175,rw,noatime,nolock,rsize=32768,wsize=32768,tcp,timeo=14
      device: ":/srv/nfs/allegutta/db-data"
