version: '3.8'

volumes:
  api-data:
  api-logs:
  db-data:
  proxy:

services:

  allegutta-proxy:
    container_name: allegutta-proxy
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - '8080:80'

  allegutta-web:
    container_name: allegutta-web
    build:
      context: .
      dockerfile: Dockerfile.web

  allegutta-api:
    container_name: allegutta-api
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      NORDNET_USERNAME: ${NORDNET_USERNAME}
      NORDNET_PASSWORD: ${NORDNET_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      # Data persistency
      - api-data:/app/data
      - api-logs:/app/logs

  allegutta-db:
    image: yobasystems/alpine-mariadb
    container_name: allegutta-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: always
