version: '3.8'

volumes:
  api-data:
  api-logs:
  proxy:

services:

  allegutta-proxy:
    container_name: allegutta-proxy
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - '8080:80'

  allegutta-web:
    container_name: allegutta-web
    build:
      context: .
      dockerfile: Dockerfile.web

  allegutta-api:
    container_name: allegutta-api
    build:
      context: .
      dockerfile: Dockerfile.api
    # env_file:
    #   - .env
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    volumes:
      # Data persistency
      - api-data:/app/data
      - api-logs:/app/logs
