version: '3.8'

volumes:
  api-data:
  api-logs:
  db-data:
  proxy:

services:

  allegutta-proxy:
    image: bisand/allegutta-proxy:latest
    container_name: allegutta-proxy
    ports:
      - '8080:80'
    restart: always

  allegutta-web:
    image: bisand/allegutta-web:latest
    container_name: allegutta-web
    depends_on:
      - allegutta-api
    restart: always

  allegutta-api:
    image: bisand/allegutta-api:latest
    container_name: allegutta-api
    depends_on:
      - allegutta-proxy
      - allegutta-db
    environment:
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      NORDNET_USERNAME: {{NORDNET_USERNAME}}
      NORDNET_PASSWORD: {{NORDNET_PASSWORD}}
      MYSQL_PASSWORD: {{MYSQL_PASSWORD}}
    volumes:
      # Data persistency
      - api-data:/app/data
      - api-logs:/app/logs
    restart: always

  allegutta-db:
    image: yobasystems/alpine-mariadb:latest
    container_name: allegutta-db
    environment:
      MYSQL_ROOT_PASSWORD: {{MYSQL_ROOT_PASSWORD}}
      MYSQL_DATABASE: {{MYSQL_DATABASE}}
      MYSQL_USER: {{MYSQL_USER}}
      MYSQL_PASSWORD: {{MYSQL_PASSWORD}}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: always
