name: Deploy allegutta

on:
  release:
    types: [published]
  push:
    branches: [main]

jobs:

  build-publish-proxy:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          tags: |
            type=semver,pattern={{version}}
          images: |
            bisand/allegutta-proxy

      - name: Set DOCKER_TAGS environment variable
        if: steps.meta.outputs.tags != null
        run: echo "DOCKER_TAGS=${{ steps.meta.outputs.tags }}" >> $GITHUB_ENV

      - name: Set alt DOCKER_TAGS environment variable
        if: steps.meta.outputs.tags == null
        run: echo "DOCKER_TAGS=${{${{ steps.meta.outputs.images }}}}:beta-${{ github.run_id }}" >> $GITHUB_ENV

      - name: Test DOCKER_TAGS environment variable
        run: echo "DOCKER_TAGS=${{ env.DOCKER_TAGS }}"

      - name: Build and push allegutta-proxy Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.proxy
          push: true
          tags: ${{ env.DOCKER_TAGS }}
          labels: ${{ steps.meta.outputs.labels }}

  build-publish-api:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          tags: |
            type=semver,pattern={{version}}
          images: |
            bisand/allegutta-api

      - name: Set DOCKER_TAGS environment variable
        if: steps.meta.outputs.tags != null
        run: echo "DOCKER_TAGS=${{ steps.meta.outputs.tags }}" >> $GITHUB_ENV

      - name: Set alt DOCKER_TAGS environment variable
        if: steps.meta.outputs.tags == null
        run: echo "DOCKER_TAGS=${{${{ steps.meta.outputs.images }}}}:beta-${{ github.run_id }}" >> $GITHUB_ENV

      - name: Test DOCKER_TAGS environment variable
        run: echo "DOCKER_TAGS=${{ env.DOCKER_TAGS }}"

      - name: Build and push allegutta-api Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: ${{ env.DOCKER_TAGS }}
          labels: ${{ steps.meta.outputs.labels }}

  build-publish-web:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          tags: |
            type=semver,pattern={{version}}
          images: |
            bisand/allegutta-web

      - name: Set DOCKER_TAGS environment variable
        if: steps.meta.outputs.tags != null
        run: echo "DOCKER_TAGS=${{ steps.meta.outputs.tags }}" >> $GITHUB_ENV

      - name: Set alt DOCKER_TAGS environment variable
        if: steps.meta.outputs.tags == null
        run: echo "DOCKER_TAGS=${{${{ steps.meta.outputs.images }}}}:beta-${{ github.run_id }}" >> $GITHUB_ENV

      - name: Test DOCKER_TAGS environment variable
        run: echo "DOCKER_TAGS=${{ env.DOCKER_TAGS }}"

      - name: Build and push allegutta-web Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.web
          push: true
          tags: ${{ env.DOCKER_TAGS }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-allegutta:
    needs: [build-publish-proxy, build-publish-web, build-publish-api]
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v3

      # This step is run when the tag is release-XXX
      - name: Sets env vars for release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "PORTAINER_ENDPOINT_ID=5" >> $GITHUB_ENV

      # This step is run when the tag is staging-XXX
      - name: Sets env vars for main
        if: startsWith(github.ref, 'refs/remotes/origin/main')
        run: |
          echo "PORTAINER_ENDPOINT_ID=4" >> $GITHUB_ENV

      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash

      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo "${{ secrets.NORDNET_USERNAME }}"
          echo "Trick to echo GitHub Actions Secret:  "
          echo "${{ secrets.NORDNET_USERNAME }}" | sed 's/./& /g' 

      - name: Deploy stack to Portainer
        uses: carlrygart/portainer-stack-deploy@v1
        with:
          # url of Poratainer instance
          portainer-host: ${{ secrets.PORTAINER_HOST }}

          # portainer auth
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}

          # internal portainer cluster id
          endpoint-id: ${{ env.PORTAINER_ENDPOINT_ID }}

          # stack name
          stack-name: allegutta

          # docker stack file location
          stack-definition: portainer-stack.yml

          # vars to substitute in stack
          template-variables: | 
            {
              "NORDNET_USERNAME":"${{ secrets.NORDNET_USERNAME }}",
              "NORDNET_PASSWORD":"${{ secrets.NORDNET_PASSWORD }}",
              "MYSQL_ROOT_PASSWORD":"${{ secrets.MYSQL_ROOT_PASSWORD }}",
              "MYSQL_DATABASE":"${{ secrets.MYSQL_DATABASE }}",
              "MYSQL_USER":"${{ secrets.MYSQL_USER }}",
              "MYSQL_PASSWORD":"${{ secrets.MYSQL_PASSWORD }}"
            }
