name: Deploy only allegutta

on:
  push:
    branches: [main]

jobs:

  deploy-allegutta:
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v3

      # - name: Sleep for 10 seconds
      #   run: sleep 10s
      #   shell: bash

      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo "${{ secrets.NORDNET_USERNAME }}"
          echo "Trick to echo GitHub Actions Secret:  "
          echo "${{ secrets.NORDNET_USERNAME }}" | sed 's/./& /g' 

      - name: Deploy stack to Portainer
        uses: carlrygart/portainer-stack-deploy@v1
        with:
          # url of Poratainer instance
          portainer-host: ${{ secrets.PORTAINER_HOST }}

          # portainer auth
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}

          # internal portainer cluster id
          endpoint-id: 4

          # stack name
          stack-name: allegutta

          # docker stack file location
          stack-definition: portainer-stack.yml

          # vars to substitute in stack
          template-variables: '{"NORDNET_USERNAME":"${{ secrets.NORDNET_USERNAME }}", "NORDNET_PASSWORD":"${{ secrets.NORDNET_PASSWORD }}", "MYSQL_ROOT_PASSWORD":"${{ secrets.MYSQL_ROOT_PASSWORD }}", "MYSQL_DATABASE":"${{ secrets.MYSQL_DATABASE }}", "MYSQL_USER":"${{ secrets.MYSQL_USER }}", "MYSQL_PASSWORD":"${{ secrets.MYSQL_PASSWORD }}"}'
