name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@4.1.1
      with:
        images: bisand/allegutta-proxy

    - name: Build allegutta.proxy Docker image
      run: docker build . --file Dockerfile.proxy --tag bisand/allegutta-proxy:$(date +%s)
    
    - name: Build allegutta.api Docker image
      run: docker build . --file Dockerfile.api --tag bisand/allegutta-api:$(date +%s)
    
    - name: Build allegutta.web Docker image
      run: docker build . --file Dockerfile.web --tag bisand/allegutta-web:$(date +%s)
