name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          bisand/allegutta-proxy
          bisand/allegutta-web
          bisand/allegutta-api

    - name: Build and push allegutta-proxy Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile.proxy
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push allegutta-web Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile.web
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push allegutta-api Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile.api
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

#    - name: Build allegutta.proxy Docker image
#      run: docker build . --file Dockerfile.proxy --tag bisand/allegutta-proxy:$(date +%s)
    
#    - name: Build allegutta.api Docker image
#      run: docker build . --file Dockerfile.api --tag bisand/allegutta-api:$(date +%s)
    
#    - name: Build allegutta.web Docker image
#      run: docker build . --file Dockerfile.web --tag bisand/allegutta-web:$(date +%s)
